### ISSUE TITLE
guessByFileCmd always results in unknown

### ISSUE THREAD

**Issue by FedericoMassaioli** [kosinix/guess-file-type#1]
Hi,
the `guessByFileCmd()` function always results in `unknown` because of a spurious `let` before redefinition of `filter` in line 76 of `index.js`.
As a consequence, when `filters` is null the `forEach()` call in line 94 fails, and the result is always `unknown`.

The issue can be worked around by passing an array if `guessByFileCmd()` is used directly and called with a second argument, however it cannot be circumvented if `guess()` is used.

**Comment by kosinix** [comment]
@FedericoMassaioli Thank you for reporting. I am looking into it.
